#!/usr/bin/env python3
"""Bake font3 = the the source game "Bank Gothic" HUD face (the condensed geometric caps the
game uses for money/health) into a PSP atlas in plain ASCII order, so CFont can use it
exactly like font1/font2 (ASCII 0x20..0x7F at tile c-0x20).

Source = fonts.txd "font2" texture (16x13 grid). The Bank Gothic glyphs live in the
LOWER block of that atlas:
  row 9 : '0'..'9' at cols 0..9,  'A'..'E' at cols 11..15
  row 10: 'F'..'U' at cols 0..15
  row 11: 'V'..'Z' at cols 0..4
It is CAPS + digits only, so lowercase maps to uppercase; punctuation/space are taken
from font2's UPPER clean block (rows 0..1, ASCII-positioned) since the HUD face has none.

Out: assets_build/font3.bin (512x512 RGBA8888, white RGB + glyph alpha) +
     src/game_sa/font3_widths.h (FONT3_W[96] proportional advances). Run:
       python tools/font3_bake.py
"""
import os, sys
sys.path.insert(0, os.environ.get("GVCS_ROOT", ""))
from gvcslib import sa_txd            # PS2-native TXD codec (Quarry: user's PS2 disc)
from PIL import Image

# INPUT: SA_ROOT env (Quarry -> user's extracted PS2 disc); PC install = dev fallback.
SA_ROOT = os.environ.get("SA_ROOT", "")
TXD   = SA_ROOT + "/models/fonts.txd"
# OUTPUT: argv[1] dir (Quarry passes <data>/hud), else the dev assets_build tree.
OUTD  = sys.argv[1] if len(sys.argv) > 1 else ""
HDR   = ""
A, COLS, ROWS = 512, 16, 13


def src_tile(c):
    """(row,col) in font2 for ASCII code c, or None for blank."""
    ch = chr(c)
    if ch == ' ':
        return None
    if '0' <= ch <= '9':
        return (9, ord(ch) - ord('0'))
    L = ch.upper()
    if 'A' <= L <= 'E':
        return (9, 11 + (ord(L) - ord('A')))
    if 'F' <= L <= 'U':
        return (10, ord(L) - ord('F'))
    if 'V' <= L <= 'Z':
        return (11, ord(L) - ord('V'))
    # punctuation/symbols: take from the upper clean block at the ASCII position
    if 0x20 <= c <= 0x3F:
        t = c - 0x20
        return (t // COLS, t % COLS)
    return None


def main():
    texs = sa_txd.decode(open(TXD, "rb").read())
    w, h, rgba = texs["font2"]
    src = Image.frombytes("RGBA", (w, h), rgba).resize((A, A), Image.BILINEAR)
    sa = src.split()[3]                          # alpha = glyph coverage
    dst = Image.new("L", (A, A), 0)

    cw = A / COLS                                 # 32
    chh = A / ROWS                                # ~39.4
    widths = [0] * 96
    for c in range(0x20, 0x80):
        di = c - 0x20
        dr, dc = di // COLS, di % COLS
        st = src_tile(c)
        if st is None:
            widths[di] = int(cw * 0.42) if c == 0x20 else int(cw * 0.30)
            continue
        sr, sc = st
        cell = sa.crop((int(sc * cw), int(sr * chh), int(sc * cw + cw), int(sr * chh + chh)))
        dst.paste(cell, (int(dc * cw), int(dr * chh)))
        # proportional advance = glyph alpha bbox width + a small side bearing
        bb = cell.getbbox()
        widths[di] = (bb[2] - bb[0] + 6) if bb else int(cw * 0.5)

    # white RGB + alpha, emit raw RGBA8888
    out = bytearray(A * A * 4)
    ap = dst.load()
    for y in range(A):
        for x in range(A):
            o = (y * A + x) * 4
            out[o] = out[o + 1] = out[o + 2] = 255
            out[o + 3] = ap[x, y]
    os.makedirs(OUTD, exist_ok=True)
    open(os.path.join(OUTD, "font3.bin"), "wb").write(out)

    # FONT3_W is engine source (already compiled in): regenerate it only in the dev
    # repo. Under the Quarry converter src/ is absent -> skip (data/ needs only the .bin).
    if os.path.isdir(os.path.dirname(HDR)):
        with open(HDR, "w") as f:
            f.write("/* generated by tools/font3_bake.py - Bank Gothic advances. */\n")
            f.write("#ifndef FONT3_W_H\n#define FONT3_W_H\n")
            f.write("static const unsigned char FONT3_W[96] = {\n")
            for i in range(0, 96, 16):
                f.write("    " + ",".join("%2d" % widths[j] for j in range(i, i + 16)) + ",\n")
            f.write("};\n#endif\n")

    # test render so the glyph mapping can be eyeballed before wiring it in
    test = Image.new("RGB", (A, 60), (0, 0, 0))
    tp = test.load()
    dl = dst.load()
    penx = 4
    for ch in "FPS 58 VIS 269 TIME 12:00":
        c = ord(ch)
        di = c - 0x20
        dr, dc = di // COLS, di % COLS
        for yy in range(int(chh)):
            for xx in range(int(cw)):
                a8 = dl[int(dc * cw) + xx, int(dr * chh) + yy]
                if a8 > 40 and penx + xx < A:
                    tp[penx + xx, yy + 8] = (a8, a8, a8)
        penx += widths[di]
    _asset = ""
    if os.path.isdir(_asset):                    # dev-only diagnostic; absent under Quarry
        test.save(os.path.join(_asset, "_font3_test.png"))
    print("wrote %s" % os.path.join(OUTD, "font3.bin"))


if __name__ == "__main__":
    main()
