#!/usr/bin/env python3
"""Bake a the source game font from fonts.txd into a PSP atlas (RGBA8888, white RGB +
glyph alpha) + an advance-width header. Port-side COPY of gvcslib/work/font_bake.py
(gvcslib is READ-ONLY). Reads the PC SA install, writes into this project.

 font1 = the clean general/subtitle font (FONT_ID 1) -> font.bin / FONT_W
 font2 = the HUD font: bold sans DIGITS (used for the clock/money) + gothic
 letters (FONT_ID 2) -> font2.bin / FONT2_W

Grid: 16 cols x 13 rows, ASCII 0x20..0x7F at tile (c-0x20), cell 32 x ~39.4 in the
512x512 source. Usage:
 python tools/font_bake.py [font1|font2]
"""
import os, sys
sys.path.insert(0, os.environ.get("GVCS_ROOT", ""))
from gvcslib import sa_txd            # PS2-native TXD codec (Quarry: user's PS2 disc)

# INPUT: SA_ROOT env (Quarry -> user's extracted PS2 disc); PC install = dev fallback.
SA_ROOT = os.environ.get("SA_ROOT", "")
TXD  = SA_ROOT + "/models/fonts.txd"
DAT  = SA_ROOT + "/data/fonts.dat"
# OUTPUT: argv[2] dir (Quarry passes <data>/hud), else the dev assets_build tree.
# (argv[1] stays the font1|font2 selector.)
OUTD = sys.argv[2] if len(sys.argv) > 2 else ""
HDRD = ""   # widths.h = engine source (dev-only)
ATLAS, COLS, ROWS = 512, 16, 13


def parse_prop(font_id, count):
    lines = open(DAT, "r", errors="replace").read().splitlines()
    cur, i = None, 0
    while i < len(lines):
        t = lines[i].split("#", 1)[0].strip()
        if t == "[FONT_ID]":
            i += 1; cur = int(lines[i].split("#", 1)[0].strip())
        elif t == "[PROP]" and cur == font_id:
            vals, i = [], i + 1
            while i < len(lines):
                body = lines[i].split("#", 1)[0].strip()
                if body.startswith("["):
                    break
                vals.extend(int(x) for x in body.split()); i += 1
            return vals[:count]
        i += 1
    # fall back to a fixed advance if the block is missing
    return [22] * count


def bake(which):
    tex = {"font1": ("font1", 1, "font.bin",  "FONT_W",  "font_widths.h"),
           "font2": ("font2", 2, "font2.bin", "FONT2_W", "font2_widths.h")}[which]
    texname, font_id, out_bin, warr, out_h = tex

    texs = sa_txd.decode(open(TXD, "rb").read())
    w, h, rgba = texs[texname]
    # white RGB + the texture's alpha channel, resized to ATLAS if needed.
    from PIL import Image
    alpha = Image.frombytes("RGBA", (w, h), rgba).split()[3].resize((ATLAS, ATLAS), Image.BILINEAR)
    ap = alpha.load()
    out = bytearray(ATLAS * ATLAS * 4)
    for y in range(ATLAS):
        for x in range(ATLAS):
            o = (y * ATLAS + x) * 4
            out[o] = 255; out[o+1] = 255; out[o+2] = 255; out[o+3] = ap[x, y]

    import os
    os.makedirs(OUTD, exist_ok=True)
    open(os.path.join(OUTD, out_bin), "wb").write(out)

    widths = parse_prop(font_id, 96)
    # FONT_W/FONT2_W is engine source (already compiled in): regenerate it only in the
    # dev repo. Under the Quarry converter src/ is absent -> skip (data/ needs only the.bin).
    if os.path.isdir(HDRD):
        with open(os.path.join(HDRD, out_h), "w") as f:
            f.write("/* generated by tools/font_bake.py - %s advance widths. */\n" % texname)
            f.write("#ifndef %s_H\n#define %s_H\n" % (warr, warr))
            f.write("static const unsigned char %s[96] = {\n" % warr)
            for i in range(0, 96, 16):
                f.write("    " + ",".join("%2d" % widths[j] for j in range(i, i + 16)) + ",\n")
            f.write("};\n#endif\n")
    print("wrote %s/%s  (font_id=%d)" % (OUTD, out_bin, font_id))


if __name__ == "__main__":
    bake(sys.argv[1] if len(sys.argv) > 1 else "font2")
