#!/usr/bin/env python3
"""skidtex_bake - bake the ORIGINAL SA tyre-skid tread mask into a compiled-in
C header (src/game_sa/SkidTex.h) for CSkidmarks.

Source: models/particle.txd -> texture "particleskid" (the SA skid-trail tread
strip). It is a 32x32 D3D9 raster whose RGB is pure white; the whole tread
pattern (vertical ribs + a diagonal scuff) lives in the ALPHA channel.

Our skid render draws the strip with a BLACK vertex colour under TFX_MODULATE,
so texture RGB is irrelevant (RGB*0 = black) - only ALPHA matters. We therefore
store ONLY the 1024-byte alpha mask (<4KB -> a .h array, no runtime asset / no
deploy). The runtime pairs it with white RGB into a GU_PSM_8888 buffer.

Alpha is peak-normalised (raw max -> 255, linear, clamped) so the tread reads at
the same intensity the tuned procedural texture gave, while preserving the
authentic pattern and its soft gaps. Idempotent; re-run after a TXD change.
"""
import os
import sys

GVCS = os.environ.get("GVCS_ROOT", "")
if GVCS not in sys.path:
    sys.path.insert(0, GVCS)
from gvcslib import sa_txd_d3d9

SA = ""
TXD = os.path.join(SA, "models", "particle.txd")
TEXNAME = "particleskid"
# Written into the worktree that this tool lives in (keeps bake+source together).
OUT_H = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "..", "src", "game_sa", "SkidTex.h")


def main():
    texs = sa_txd_d3d9.decode(open(TXD, "rb").read())
    low = {k.lower(): k for k in texs}
    if TEXNAME not in low:
        print("! %s not in %s (have: %s)" % (TEXNAME, TXD, sorted(low)))
        return 1
    w, h, rgba = texs[low[TEXNAME]]
    n = w * h

    alpha = [rgba[i * 4 + 3] for i in range(n)]
    rgb_white = all(rgba[i * 4] == 255 and rgba[i * 4 + 1] == 255 and
                    rgba[i * 4 + 2] == 255 for i in range(n))
    amin, amax = min(alpha), max(alpha)
    amean = sum(alpha) // n

    # peak-normalise: raw amax -> 255 (linear from 0, clamp). Preserves the soft
    # low end (gaps/edges stay translucent, no black-crush) and relative contrast.
    scale = 255.0 / amax if amax else 1.0
    norm = [min(255, int(a * scale + 0.5)) for a in alpha]

    lines = []
    for y in range(h):
        row = norm[y * w:(y + 1) * w]
        lines.append("    " + ",".join("%3d" % v for v in row) + ",")
    body = "\n".join(lines)

    header = f"""/* SkidTex.h - GENERATED by tools/skidtex_bake.py. DO NOT EDIT BY HAND.
 *
 * Original SA tyre-skid tread mask: "{TEXNAME}" from models/particle.txd
 * ({w}x{h}, D3D9 TXD). Source RGB is pure white ({"verified" if rgb_white else
 "!! NOT white - check"}); the whole tread pattern lives in ALPHA.
 * Raw alpha: min {amin} max {amax} mean {amean}. Stored peak-normalised
 * (x255/{amax}, clamp) so the tread reads at the tuned intensity while keeping
 * the authentic pattern + soft gaps. Only ALPHA is kept ({n} bytes): the runtime
 * pairs it with white RGB, and the BLACK vertex colour under TFX_MODULATE makes
 * RGB irrelevant. */
#ifndef SA_SKIDTEX_H
#define SA_SKIDTEX_H

#define SKIDTEX_W {w}
#define SKIDTEX_H {h}

/* per-texel alpha, row-major (x = across the mark width / U, y = along it / V) */
static const unsigned char g_skidTexAlpha[SKIDTEX_W * SKIDTEX_H] = {{
{body}
}};

#endif /* SA_SKIDTEX_H */
"""
    outp = os.path.normpath(OUT_H)
    open(outp, "w", newline="\n").write(header)
    print("skidtex_bake: %s '%s' %dx%d  alpha raw[min %d max %d mean %d] "
          "-> normalised peak 255  RGB_white=%s" %
          (os.path.basename(TXD), TEXNAME, w, h, amin, amax, amean, rgb_white))
    print("  wrote %s (%d alpha bytes, compiled-in, no deploy)" % (outp, n))
    return 0


if __name__ == "__main__":
    sys.exit(main())
